/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CategoryCount = IDL.Record({
  'count' : IDL.Nat,
  'category' : IDL.Text,
});
export const ConsentSettings = IDL.Record({
  'shareAge' : IDL.Bool,
  'shareLocation' : IDL.Bool,
  'shareInterests' : IDL.Bool,
});
export const Demographics = IDL.Record({
  'ageRange' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'consent' : ConsentSettings,
  'interests' : IDL.Vec(IDL.Text),
  'demographics' : Demographics,
});
export const CompanyProfile = IDL.Record({
  'productCategory' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCategoryCounts' : IDL.Func([], [IDL.Vec(CategoryCount)], ['query']),
  'getAudienceCountCategory' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CompanyProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanyProfile' : IDL.Func([CompanyProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CategoryCount = IDL.Record({
    'count' : IDL.Nat,
    'category' : IDL.Text,
  });
  const ConsentSettings = IDL.Record({
    'shareAge' : IDL.Bool,
    'shareLocation' : IDL.Bool,
    'shareInterests' : IDL.Bool,
  });
  const Demographics = IDL.Record({
    'ageRange' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'consent' : ConsentSettings,
    'interests' : IDL.Vec(IDL.Text),
    'demographics' : Demographics,
  });
  const CompanyProfile = IDL.Record({
    'productCategory' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCategoryCounts' : IDL.Func([], [IDL.Vec(CategoryCount)], ['query']),
    'getAudienceCountCategory' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CompanyProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanyProfile' : IDL.Func([CompanyProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };